packages:
  - .
allowBuilds:
  core-js-pure: true
  esbuild: true
  lefthook: true
  nx: true
minimumReleaseAgeExclude:
  - tsx@4.23.12
onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - lefthook
  - nx
